# Generated by Django 3.1.5 on 2021-01-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210113_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='_set',
            new_name='set',
        ),
    ]
