# Generated by Django 3.1.5 on 2021-01-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210113_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('single', 'single out'), ('master', 'master out'), ('double', 'double out')], max_length=64),
        ),
    ]
